<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rahul" failures="3" tests="5" name="InnvationCountTest" time="46.803" errors="0" timestamp="2024-03-24T21:49:24 IST">
  <testcase classname="InnvocationCount.TestInvocationCount" name="validLoginTest" time="5.735"/>
  <testcase classname="InnvocationCount.TestInvocationCount" name="validLoginTest" time="4.555"/>
  <testcase classname="InnvocationCount.TestInvocationCount" name="verifyLinkedIn" time="4.523">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at InnvocationCount.TestInvocationCount.verifyLinkedIn(TestInvocationCount.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinkedIn -->
  <testcase classname="InnvocationCount.TestInvocationCount" name="verifyLinkedIn" time="4.392">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at InnvocationCount.TestInvocationCount.verifyLinkedIn(TestInvocationCount.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinkedIn -->
  <testcase classname="InnvocationCount.TestInvocationCount" name="verifyLinkedIn" time="4.477">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at InnvocationCount.TestInvocationCount.verifyLinkedIn(TestInvocationCount.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinkedIn -->
</testsuite> <!-- InnvationCountTest -->
